name: NHS Mental Health Job Alert

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  send-email:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

        run: python main.py
